In [2]:
import pandas as pd
fandango = pd.read_csv('./fandango_score.csv')

In [3]:
fandango.loc[:2]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5

In [4]:
# Shared Indexes
film_series = fandango['FILM']
rt_series = fandango['RottenTomatoes']

In [5]:
from pandas import Series

film_names = film_series.values
rt_scores = rt_series.values

In [6]:
type(rt_series)

pandas.core.series.Series

In [7]:
type(rt_scores)

numpy.ndarray

In [8]:
series_custom = Series(rt_scores, film_names)
series_custom.head()

Avengers: Age of Ultron (2015)    74
Cinderella (2015)                 85
Ant-Man (2015)                    80
Do You Believe? (2015)            18
Hot Tub Time Machine 2 (2015)     14
dtype: int64

In [9]:
# Even though series_custom has strings for its index, it still has an internal numerical index that can be accessed
series_custom[['Minions (2015)', 'Leviathan (2014)']]
series_custom[5:11]

The Water Diviner (2015)             63
Irrational Man (2015)                42
Top Five (2014)                      86
Shaun the Sheep Movie (2015)         99
Love & Mercy (2015)                  89
Far From The Madding Crowd (2015)    84
dtype: int64

In [10]:
# To resort series_custom alphabetically
# Return a list representation of the current index using tolist().
original_index = series_custom.index
# Sort the index with sorted().
sorte = sorted(original_index)
# Use reindex() to set the newly-ordered index.
sorted_by_index = series_custom.reindex(sorte)
sorted_by_index.head()

'71 (2015)                    97
5 Flights Up (2015)           52
A Little Chaos (2015)         40
A Most Violent Year (2014)    90
About Elly (2015)             97
dtype: int64

In [11]:
# Or just use the pandas method
sc2 = series_custom.sort_index()
sc3 = series_custom.sort_values()

In [12]:
# Can apply numpy functions like np.add or np.max
# Or just plain operators
normalized_score = series_custom/20

rt_critics and rt_users are Series objects containing the average ratings from critics and users for each film.
Both Series objects use the same custom string index, which they base on the film names. Using the Python arithmetic operators to return a new Series object, rt_mean, that contains the mean ratings from both critics and users for each film.

In [13]:
rt_critics = Series(fandango['RottenTomatoes'].values, index=fandango['FILM'])
rt_users = Series(fandango['RottenTomatoes_User'].values, index=fandango['FILM'])
rt_mean = (rt_critics + rt_users)/2

In [19]:
fandango.index

RangeIndex(start=0, stop=146, step=1)

In [20]:
# First five rows
fandango[0:5]
# From row at 140 and higher
fandango[140:]
# Just row at index 50
fandango.iloc[50]
# Just row at index 45 and 90
fandango.iloc[[45,90]]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
45,Tomorrowland (2015),50,53,60,6.4,6.6,4.0,3.7,2.5,2.65,...,3.30,2.5,2.5,3.0,3.0,3.5,262,42937,8077,0.3
90,The SpongeBob Movie: Sponge Out of Water (2015),78,55,62,6.5,6.1,3.5,3.3,3.9,2.75,...,3.05,4.0,3.0,3.0,3.5,3.0,196,26046,4493,0.2

In [21]:
# drop = False will keep the column set as index
# inplace = True will replace the original instead of having to assign it to a new var
fandango_films = fandango.set_index('FILM', drop=False)
print(fandango_films.index)

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

In [24]:
fandango_films.iloc[:1]
# kept the FILM column but also has FILM for the index

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.7,4.3,...,3.9,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5

In [27]:
best_movies_ever = fandango_films.loc[['The Lazarus Effect (2015)', "Gett: The Trial of Viviane Amsalem (2015)", "Mr. Holmes (2015)"]]
best_movies_ever

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
The Lazarus Effect (2015),The Lazarus Effect (2015),14,23,31,4.9,5.2,3.0,3.0,0.70,1.15,...,2.6,0.5,1.0,1.5,2.5,2.5,62,17691,1651,0.0
Gett: The Trial of Viviane Amsalem (2015),Gett: The Trial of Viviane Amsalem (2015),100,81,90,7.3,7.8,3.5,3.5,5.00,4.05,...,3.9,5.0,4.0,4.5,3.5,4.0,19,1955,59,0.0
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.7,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0

In [26]:
# Slice using either bracket notation or loc[]
fandango_films["Avengers: Age of Ultron (2015)":"Hot Tub Time Machine 2 (2015)"]
fandango_films.loc["Avengers: Age of Ultron (2015)":"Hot Tub Time Machine 2 (2015)"]

# Specific movie
fandango_films.loc['Kumiko, The Treasure Hunter (2015)']

# Selecting list of movies
movies = ['Kumiko, The Treasure Hunter (2015)', 'Do You Believe? (2015)', 'Ant-Man (2015)']
fandango_films.loc[movies]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
"Kumiko, The Treasure Hunter (2015)","Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0
Do You Believe? (2015),Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.20,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
Ant-Man (2015),Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.50,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5

## The apply() method in pandas allows us to specify Python logic that we want to evaluate over the Series objects in a dataframe. Here

In [31]:
# Calculate the standard deviations for each numeric column
import numpy as np

# returns a Series of the datatypes of the columns
types = fandango_films.dtypes
# filter data types to just floats, index attributes returns just column names
float_columns = types[types.values == 'float64'].index
# use bracket notation to filter columns to just float columns
float_df = fandango_films[float_columns]

# `x` is a Series object representing a column
deviations = float_df.apply(lambda x: np.std(x))

print(deviations)

Metacritic_User               1.505529
IMDB                          0.955447
Fandango_Stars                0.538532
Fandango_Ratingvalue          0.501106
RT_norm                       1.503265
RT_user_norm                  0.997787
Metacritic_norm               0.972522
Metacritic_user_nom           0.752765
IMDB_norm                     0.477723
RT_norm_round                 1.509404
RT_user_norm_round            1.003559
Metacritic_norm_round         0.987561
Metacritic_user_norm_round    0.785412
IMDB_norm_round               0.501043
Fandango_Difference           0.152141
dtype: float64

In [39]:
# just straight up doubling each column
double_df = float_df.apply(lambda x: x*2)
double_df.head(3)

,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,Metacritic_norm,Metacritic_user_nom,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Fandango_Difference
FILM,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),14.2,15.6,10.0,9.0,7.4,8.6,6.6,7.1,7.8,7.0,9.0,7.0,7.0,8.0,1.0
Cinderella (2015),15.0,14.2,10.0,9.0,8.5,8.0,6.7,7.5,7.1,9.0,8.0,7.0,8.0,7.0,1.0
Ant-Man (2015),16.2,15.6,10.0,9.0,8.0,9.0,6.4,8.1,7.8,8.0,9.0,6.0,8.0,8.0,1.0

In [43]:
rt_mt_user = float_df[['RT_user_norm', 'Metacritic_user_nom']]
# Need to set axis=1 so that this transformation is applied to the rows
# Applying over the rows allows us to do things like calculate the 
# standard deviation of multiple column values for each movie:
rt_mt_deviations = rt_mt_user.apply(lambda x: np.std(x), axis=1)
rt_mt_deviations[0:5]

FILM
Avengers: Age of Ultron (2015)    0.375
Cinderella (2015)                 0.125
Ant-Man (2015)                    0.225
Do You Believe? (2015)            0.925
Hot Tub Time Machine 2 (2015)     0.150
dtype: float64

In [46]:
rt_mt_means = rt_mt_user.apply(lambda x: np.mean(x), axis=1)
rt_mt_means[0:5]

FILM
Avengers: Age of Ultron (2015)    3.925
Cinderella (2015)                 3.875
Ant-Man (2015)                    4.275
Do You Believe? (2015)            3.275
Hot Tub Time Machine 2 (2015)     1.550
dtype: float64